
default:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: 'dbt.duckdb'
      schema: main
    qua:
      type: duckdb
      path: 'dbt.duckdb'
      schema: qua
    prd:
      type: duckdb
      path: 'dbt.duckdb'
      schema: prd
    feature:
      type: duckdb
      path: 'dbt.duckdb'
      schema: "{{ env_var('DBT_FEATURE_SCHEMA') }}"
