version: 2

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - not_null

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - not_null

  - name: dim_customers
    columns:
      - name: customer_key
        tests:
          - unique
          - not_null

  - name: fact_orders
    columns:
      - name: order_key
        tests:
          - unique
          - not_null
