name: dbt CI/CD

on:
  push:
    branches:
      - main
      - dev
      - qua
      - prd
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core

      - name: Run dbt
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            dbt run --target prd
          elif [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            dbt run --target dev
          elif [[ "${{ github.ref }}" == "refs/heads/qua" ]]; then
            dbt run --target qua
          else
            dbt run --target feature --vars '{ "schema_name": "${{ github.head_ref }}" }'
          fi